"""edit user and address model

Revision ID: 127b76864954
Revises: ca98ef3fd4ee
Create Date: 2025-08-06 13:05:03.714984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '127b76864954'
down_revision: Union[str, Sequence[str], None] = 'ca98ef3fd4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('addresses', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'phone_number')
    # ### end Alembic commands ###
