"""add refresh token to refreshtoken table

Revision ID: ca98ef3fd4ee
Revises: 766a4d787754
Create Date: 2025-08-05 15:18:24.339977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca98ef3fd4ee'
down_revision: Union[str, Sequence[str], None] = '766a4d787754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_refreshtoken_refresh_token'), 'refreshtoken', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtoken_refresh_token'), table_name='refreshtoken')
    op.drop_column('refreshtoken', 'refresh_token')
    # ### end Alembic commands ###
