"""edit ondelete

Revision ID: ce2052903584
Revises: e352df9744b9
Create Date: 2025-09-02 11:32:18.629126

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2052903584'
down_revision: Union[str, Sequence[str], None] = 'e352df9744b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_brands_uid'), 'brands', ['uid'], unique=False)
    op.create_table('categories',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('parent_uid', sa.Uuid(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_categories_uid'), 'categories', ['uid'], unique=False)
    op.create_table('product_attributes',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('product_type_uid', sa.Uuid(), nullable=False),
    sa.Column('attribute_type', sa.Enum('INTEGER', 'STRING', 'FLOAT', name='attributetype'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_product_attributes_uid'), 'product_attributes', ['uid'], unique=False)
    op.create_table('product_attributes_values',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('product_uid', sa.Uuid(), nullable=False),
    sa.Column('product_attribute_uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('product_uid', 'product_attribute_uid')
    )
    op.create_index(op.f('ix_product_attributes_values_uid'), 'product_attributes_values', ['uid'], unique=False)
    op.create_index('ix_unique_attr_value_ci', 'product_attributes_values', [sa.literal_column("lower('value')")], unique=True)
    op.create_table('product_images',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_uid', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_product_images_uid'), 'product_images', ['uid'], unique=False)
    op.create_table('product_types',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_product_types_uid'), 'product_types', ['uid'], unique=False)
    op.create_table('products',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_type_uid', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_products_uid'), 'products', ['uid'], unique=False)
    op.create_table('product_category_link',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_uid', sa.Uuid(), nullable=False),
    sa.Column('category_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_uid'], ['categories.uid'], ),
    sa.ForeignKeyConstraint(['product_uid'], ['products.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'product_uid', 'category_uid')
    )
    op.create_index(op.f('ix_product_category_link_uid'), 'product_category_link', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_category_link_uid'), table_name='product_category_link')
    op.drop_table('product_category_link')
    op.drop_index(op.f('ix_products_uid'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_types_uid'), table_name='product_types')
    op.drop_table('product_types')
    op.drop_index(op.f('ix_product_images_uid'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_unique_attr_value_ci', table_name='product_attributes_values')
    op.drop_index(op.f('ix_product_attributes_values_uid'), table_name='product_attributes_values')
    op.drop_table('product_attributes_values')
    op.drop_index(op.f('ix_product_attributes_uid'), table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index(op.f('ix_categories_uid'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_uid'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
